### ISSUE TITLE
example microservices with kubernetes and cloud

### ISSUE THREAD

**Issue by pokgak** [pokgak/cloud-wp-ws19#4]
# Current Design

A reverse proxy sits in front of the backend services and it is the only service that is exposed to the public. The backend services are all in a private network. They can talk to each other and the reverse proxy but the public can only reach these services through the reverse proxy.

## Components needed

- service discovery
  - enable loosely-coupled communication between containers (no need to know ip of the containers)
  - Kubernetes offer [service discovery through DNS](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#dns)

## TODO

- [x] deploy multi-service "hello world" application with kubernetes - see [wiki](https://github.com/pokgak/cloud-wp-ws19/wiki/Deploying-to-Kubernetes)
- [x] Test service discovery with kubernetes - see source code for [FrontEndApplication in kubernetes-hello-world example](TODO)
- [x] document workflow deploying application using kubernetes - see [wiki](https://github.com/pokgak/cloud-wp-ws19/wiki/Deploying-to-Kubernetes)
