### ISSUE TITLE
Setup pipeline with Travis-CI

### ISSUE THREAD

**Issue by pokgak** [pokgak/cloud-wp-ws19#5]
# TODO

- [ ] how to run tests?
- [ ] how to do continuous deployment to cloud (GCP, Azure)?
- [ ] workflow when using CI/CD? push to master? PR?
- [ ] setup CI for hello-world application and deploy to cloud using CD

**Comment by pokgak** [comment]
Links:

- [CI/CD tutorial from Travis CI](https://blog.travis-ci.com/2019-05-30-setting-up-a-ci-cd-process-on-github)

**Comment by pokgak** [comment]
problem with travis-ci not detecting the repo. considering migrating to gitlab if still cannot get it to work by tomorrow.
